use_frameworks!

platform :ios, '8.0'

target 'WGObjecTool_Example' do
  pod 'WGObjecTool', :path => '../'

  target 'WGObjecTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
